### ISSUE TITLE
Potential bug in HMUniversiality

### ISSUE THREAD

**Issue by boreng0817** [HM4725/The-Art-of-Multiprocessor-Programming#1]
https://github.com/HM4725/The-Art-of-Multiprocessor-Programming/blob/9210a2cc0ffdaa3ef3ddbaf585213c39d9a7f0db/chapter6/include/universal.hpp#L149-L153

Between line 151-152, there's **a vulnerability window** that could cause segmentation fault due to invalid structure of log list.
Using locking mechanism might violate Lock-free property, but it would solve this problem. Or, use other clever idea to solve it.

Thx.

**Comment by HM4725** [comment]
Awesome!
Pull request please!

**Comment by HM4725** [comment]
Reopen

**Comment by HM4725** [comment]
Pull Request Please

**Comment by hgs3896** [comment]
What a wonderful rendezvous spot for the concurrency discussion!

**Comment by HM4725** [comment]
@hgs3896, @boreng0817 
Can you review [Fix issue#1](https://github.com/HM4725/The-Art-of-Multiprocessor-Programming/pull/2) please?
